### ISSUE TITLE
Show which breast was fed after stopping feeding timer

### ISSUE THREAD

**Issue by P9k** [MrApplejuice/BabyBuddyAndroid#39]
Just a little idea for improving the usefulness of your app: 

Show little symbols next to the breast icon indicating which breasts were used for feeding.  Maybe something like [this](https://www.flaticon.com/free-icon/letter-l_3665947) and [this](https://www.flaticon.com/free-icon/letter-r_3665973) for left and right, respectively. 

This would be a helpful memory aid to the mother if only one breast was used in one feeding session. :-)

**Comment by MrApplejuice** [comment]
Yeah, easy enough. That was a proposal here as well, just to enrich the information in the overview. Very doable :+1:

**Comment by P9k** [comment]
> Very doable +1

Happy to hear you like the idea :)
